name: Build and Publish Plugin

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    name: Build and Publish
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'adopt'
          
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        
      - name: Extract Version from Tag
        id: get_version
        run: |
          TAG=${{ github.ref_name }}
          VERSION=${TAG#v}
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Extracted version: $VERSION"
          
      - name: Update Plugin Version
        run: |
          echo "pluginVersion=$VERSION" > gradle.properties
          echo "Updated gradle.properties with version $VERSION"
          
      - name: Build Plugin
        run: ./gradlew buildPlugin
        
      - name: Run Tests
        run: ./gradlew test
        
      - name: Verify Plugin
        run: ./gradlew runPluginVerifier
        
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: plugin-build
          path: build/distributions/ltu-progress-bar-${{ env.VERSION }}.zip
          
      - name: Publish Plugin
        if: success()
        run: ./gradlew publishPlugin
        env:
          JETBRAINS_MARKETPLACE_TOKEN: ${{ secrets.JETBRAINS_MARKETPLACE_TOKEN }}
